#!/usr/bin/with-contenv bash
set -e

NFSMODE="${NFSMODE:-SERVER}";
STATD_PORT="${STATD_PORT:-32765}";
STATD_OUTGOING_PORT="${STATD_OUTGOING_PORT:-32766}";
STATD_ARGS="${STATD_ARGS:- --port $STATD_PORT --outgoing-port $STATD_OUTGOING_PORT -F -d}";

# dont run statd if not server
if [ "${NFSMODE^^}" = "SERVER" ];
then
    echo "Starting statd...";
    exec \
        rpc.statd ${STATD_ARGS};
else
    echo "Skip Starting statd for client...";
    sleep infinity;
fi;

