#!/usr/bin/with-contenv bash
set -e

vecho () { if [ "${S6_VERBOSITY:-1}" -gt 0 ]; then echo "[$0] $@"; fi; }

RPCBIND_ARGS="${RPCBIND_ARGS:- -fw}";

vecho "Starting rpcbind...";
exec \
    rpcbind \
    ${RPCBIND_ARGS} \
    ;

